### ISSUE TITLE
Упрощение проверки на null-safe 

### ISSUE THREAD

**Issue by ABashkirova** [kozlyakov-m/StringSortKotlin#1]
Для проверки на null можно использовать [оператор elvis](https://kotlinlang.org/docs/reference/null-safety.html#elvis-operator)  
https://github.com/kozlyakov-m/StringSortKotlin/blob/967e4497e0dec9d41270e803bf499fbbeacf9e19/src/Lvl4.kt#L8
Тогда вместо if-else, можно написать так:
```
val counter: Int = result[str] ?: 0
result.put(str, counter+1)
```

**Comment by kozlyakov-m** [comment]
Спасибо. Надо читать документацию)
