### ISSUE TITLE
Лишние действия (Задача №4)

### ISSUE THREAD

**Issue by petrsed** [kozlyakov-m/StringSortKotlin#3]
1) Лучше использовать для подсчёта количества вхождений `.groupingBy{it}.eachCount()`
2) Для вывода, удобней использовать ` .forEach`.
Это всё сокращает код и делает его элегантным)
[Документация по функциям](https://kotlinlang.org/docs/reference/)

**Comment by kozlyakov-m** [comment]
Согласен, получается лаконично.
Занимательный факт: ты не заметил, что в этой задаче я забыл сделать сортировку)
